name: Trigger Main Repo Build

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'HowTo/**'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Main Repo Build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: ${{ secrets.BUILD_REPO_NAME }}
          event-type: build
          client-payload: |
            {
              "branch": "${{ github.ref }}",
              "commit": "${{ github.sha }}"
            }
